### PR TITLE
Add recommendations for Docker under Mac

### PR DESCRIPTION
**Pull request by oggy-dfin**
Thank you for your contribution to the IC Developer Portal.
Before submitting your Pull Request, please make sure that:

- [ ] You have updated the [`.github/CODEOWNERS`](https://github.com/dfinity/portal/blob/master/.github/CODEOWNERS) file according to your changes.
- [ ] You have registered new documents to [`/sidebars.js`](https://github.com/dfinity/portal/blob/master/sidebars.js) if any.

### CODE REVIEW

**Comment by mraszyk** [comment]
I'm not sure if it's a good idea to link my bug because of Peter Maydell's response: "I'm completely confused. You have an aarch64 host (that's the M1 mac), and you're running qemu-system-aarch64 with the hvf accelerator, so that gives you an aarch64 VM (using hardware acceleration). So I have no idea at all where the x86-64 stuff is happening. I think you're going to have to give us a repro case that isn't tangled up with docker and whatever this 'nerdctl' thing is, something that just uses QEMU itself."
I had the feeling that Docker and qemu are blaming each other so I'm not sure we want to link some issues explicitly.

**Comment by mraszyk** [comment]
Would you also like to include https://github.com/lima-vm/lima?

**Comment by oggy-dfin** [comment]
I removed the link to the concrete bug now. `colima` uses `lima` under the hood, so I hope that it would work as well as `lima`, but I'm not sure - how did you go about using `lima`? Installing a Linux VM and then running docker build inside of that?

**Comment by mraszyk** [comment]
> how did you go about using `lima`? Installing a Linux VM and then running docker build inside of that?

I used
```Running containerd containers (compatible with Docker containers)
$ lima nerdctl run -d --name nginx -p 127.0.0.1:8080:80 nginx:alpine
```
from the README at https://github.com/lima-vm/lima if I remember correctly.

**Pull request merged**
